-- Phase 5 M17: the Project Brain — one persisted, structured analysis of a
-- project's repository (stack, architecture, conventions, testing setup,
-- important files), generated by `brain::analyze_project` (file-scanning
-- context + one structured Anthropic call, see that module's docs) and kept
-- until the repo meaningfully changes (`brain::should_regenerate`). Exactly
-- one row per project — a second `regenerate_project_brain` call replaces it
-- in place (`db::repository::project_brain::upsert`) rather than ever
-- accumulating history, since only the latest understanding of a project is
-- useful here (unlike `reviews`, where every past verdict stays meaningful).
-- `*_json` columns are the raw structured output arrays/strings, serialized
-- the same way `reviews.findings_json` is — parsed back into real typed
-- values only at the `commands::brain_commands::ProjectBrainDto` boundary.
CREATE TABLE project_brain (
  id TEXT PRIMARY KEY,
  project_id TEXT UNIQUE NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  stack_json TEXT NOT NULL,
  architecture_json TEXT NOT NULL,
  conventions_json TEXT NOT NULL,
  testing_json TEXT NOT NULL,
  important_files_json TEXT NOT NULL,
  generated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  source_commit_sha TEXT NOT NULL
);
