import { useEffect, useState } from "react";
import { BrainCircuit, FileCode2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/empty-states/EmptyState";
import { useProjectStore } from "@/stores/useProjectStore";
import { getProjectBrain, regenerateProjectBrain } from "@/lib/tauri";
import type { ProjectBrainDto } from "@/types/db";

export interface ProjectBrainTabProps {
  projectId: string;
}

function errorMessage(err: unknown): string {
  if (typeof err === "string") return err;
  if (err instanceof Error) return err.message;
  return String(err);
}

function formatTimestamp(iso: string): string {
  return new Date(iso).toLocaleString();
}

/** One labeled section of the Brain panel's layout — a title plus a list of real values, or an honest "none found". */
function Section({ title, values }: { title: string; values: string[] }) {
  return (
    <div className="flex flex-col gap-1.5 rounded-md border border-border p-3">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-subtle-foreground">{title}</h3>
      {values.length === 0 ? (
        <p className="text-sm text-muted-foreground">None found.</p>
      ) : (
        <div className="flex flex-wrap gap-1.5">
          {values.map((value) => (
            <Badge key={value} variant="secondary">
              {value}
            </Badge>
          ))}
        </div>
      )}
    </div>
  );
}

/**
 * Phase 5 M17: the Project Brain panel — a persisted, real understanding of
 * the opened project (stack, architecture, conventions, testing setup,
 * important files), generated by analyzing the project's own repository
 * content. Renders four honest states: loading, "not yet analyzed" (no
 * brain has ever been generated), the real analysis once one exists, and a
 * real error if a regeneration attempt failed (e.g. no API key configured)
 * — never a fabricated summary.
 */
export function ProjectBrainTab({ projectId }: ProjectBrainTabProps) {
  const rootPath = useProjectStore((s) => s.projects.find((p) => p.id === projectId)?.rootPath);

  const [brain, setBrain] = useState<ProjectBrainDto | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [regenerateError, setRegenerateError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    setLoadError(null);
    getProjectBrain(projectId)
      .then((result) => {
        if (cancelled) return;
        setBrain(result);
      })
      .catch((err) => {
        if (!cancelled) setLoadError(errorMessage(err));
      })
      .finally(() => {
        if (!cancelled) setIsLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [projectId]);

  const handleRegenerate = async () => {
    setIsRegenerating(true);
    setRegenerateError(null);
    try {
      const result = await regenerateProjectBrain(projectId);
      setBrain(result);
    } catch (err) {
      setRegenerateError(errorMessage(err));
    } finally {
      setIsRegenerating(false);
    }
  };

  if (!rootPath) {
    return <EmptyState icon={BrainCircuit} title="No project open" description="Open a project to see its Project Brain." />;
  }

  const regenerateButton = (
    <Button size="sm" onClick={() => void handleRegenerate()} disabled={isRegenerating}>
      {isRegenerating ? "Analyzing…" : brain ? "Regenerate" : "Analyze project"}
    </Button>
  );

  return (
    <div className="flex flex-1 flex-col gap-3 overflow-y-auto">
      <div className="flex items-center justify-between">
        <h2 className="text-sm font-medium text-foreground">Project Brain</h2>
        {!isLoading && regenerateButton}
      </div>

      {regenerateError && (
        <div className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-xs text-destructive">
          Analysis failed: {regenerateError}
        </div>
      )}

      {isLoading ? (
        <p className="text-xs text-muted-foreground">Loading…</p>
      ) : loadError ? (
        <div className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-xs text-destructive">{loadError}</div>
      ) : isRegenerating ? (
        <EmptyState icon={BrainCircuit} title="Analyzing…" description="Gathering real repository context and running the analysis — this can take a few seconds." />
      ) : !brain ? (
        <EmptyState
          icon={BrainCircuit}
          title="Not yet analyzed"
          description="This project hasn't been analyzed yet. Click 'Analyze project' to generate a real, structured understanding of its stack, architecture, conventions, and testing setup."
        />
      ) : (
        <div className="flex flex-col gap-3">
          <div className="flex flex-col gap-1.5 rounded-md border border-border p-3">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-subtle-foreground">Architecture</h3>
            <p className="whitespace-pre-wrap text-sm text-foreground">{brain.architecture}</p>
          </div>

          <Section title="Stack" values={brain.stack} />
          <Section title="Conventions" values={brain.conventions} />
          <Section title="Testing" values={brain.testing} />

          <div className="flex flex-col gap-1.5 rounded-md border border-border p-3">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-subtle-foreground">Important files</h3>
            {brain.importantFiles.length === 0 ? (
              <p className="text-sm text-muted-foreground">None found.</p>
            ) : (
              <ul className="flex flex-col gap-1.5">
                {brain.importantFiles.map((file) => (
                  <li key={file.path} className="flex items-start gap-2 text-sm">
                    <FileCode2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-subtle-foreground" />
                    <div>
                      <code className="rounded bg-surface px-1.5 py-0.5 text-xs text-foreground">{file.path}</code>
                      <span className="ml-2 text-muted-foreground">{file.why}</span>
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </div>

          <p className="text-[11px] text-subtle-foreground">
            Generated {formatTimestamp(brain.generatedAt)} from commit <code>{brain.sourceCommitSha.slice(0, 10) || "(no commits)"}</code>
          </p>
        </div>
      )}
    </div>
  );
}
